### ISSUE TITLE
Exception downloading script - not a primitive

### ISSUE THREAD

**Issue by mikebski** [chovanecm/snow-script-sync#9]
Apr 20, 2019 2:06:19 PM cz.chovanecm.snow.datalayer.rest.dao.AutomatedTestScriptRestDao jsonObjectToSnowScript
SEVERE: Exception occurred
com.github.jsonj.exceptions.JsonTypeMismatchException: not a primitive
	at com.github.jsonj.JsonObject.asPrimitive(JsonObject.java:62)
	at com.github.jsonj.JsonObject.getString(JsonObject.java:130)
	at cz.chovanecm.snow.datalayer.rest.dao.AutomatedTestScriptRestDao.jsonObjectToSnowScript(AutomatedTestScriptRestDao.java:50)

**Comment by mikebski** [comment]
It looks like this change is causing this issue for me: 

https://github.com/chovanecm/snow-script-sync/commit/2e65ae74caa842d5c5fec3a71eb3414f9210554d#diff-e2a322b39c15b921e67190d7a06426ea

I'm testing with a London instance, what instance are you testing with?

**Comment by chovanecm** [comment]
I was using it with Jakarta, but I think this is a bug. I’ll check it hopefully today.
